import re

from models import Schema
from modules.dbapi_compat import (
    _create_table_name, _split_script, _translate_ddl,
    order_schema_statements_by_foreign_keys,
)


def test_complete_initial_schema_is_valid_for_postgresql_identity():
    translated = ";\n".join(
        _translate_ddl(statement) for statement in _split_script(Schema.get_schema_sql())
    )
    assert not re.search(r"\bAUTOINCREMENT\b", translated, re.I)
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated

    users = re.search(
        r"CREATE TABLE IF NOT EXISTS usuarios_app\s*\((.*?)\)\s*;",
        translated,
        re.I | re.S,
    )
    assert users
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in users.group(1)


def test_initial_schema_places_all_fk_parents_before_children():
    statements = order_schema_statements_by_foreign_keys(_split_script(Schema.get_schema_sql()))
    positions = {
        name: index for index, statement in enumerate(statements)
        if (name := _create_table_name(statement))
    }
    for index, statement in enumerate(statements):
        for parent in re.findall(r"\bREFERENCES\s+([A-Za-z_]\w*)\s*\(", statement, re.I):
            if parent.lower() in positions:
                assert positions[parent.lower()] < index, (parent, _create_table_name(statement))


def test_postgresql_incremental_ddl_is_idempotent():
    alter = _translate_ddl("ALTER TABLE gp_planeaciones ADD COLUMN ruta_archivo TEXT")
    index = _translate_ddl("CREATE UNIQUE INDEX idx_demo ON demo(nombre)")
    assert "ADD COLUMN IF NOT EXISTS ruta_archivo" in alter
    assert "CREATE UNIQUE INDEX IF NOT EXISTS idx_demo" in index
