import re

from models import Schema
from modules.dbapi_compat import _split_script, _translate_ddl


def test_complete_initial_schema_is_valid_for_postgresql_identity():
    translated = ";\n".join(
        _translate_ddl(statement) for statement in _split_script(Schema.get_schema_sql())
    )
    assert not re.search(r"\bAUTOINCREMENT\b", translated, re.I)
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated

    users = re.search(
        r"CREATE TABLE IF NOT EXISTS usuarios_app\s*\((.*?)\)\s*;",
        translated,
        re.I | re.S,
    )
    assert users
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in users.group(1)
