(function(){
'use strict';
const API=()=>`${window.backendUrl||window.getBackendUrl?.()||window.location.origin}/api/familias-redes`;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const role=()=>String(window.usuarioActual?.rol||window.authUser?.()?.rol||'').toUpperCase();
const canEdit=()=>['SUPERADMIN','GERENTE','COORDINADOR','PSICOSOCIAL'].includes(role());
const canApprove=()=>['SUPERADMIN','GERENTE','COORDINADOR'].includes(role());
const state={initialized:false,dashboard:null,families:[],activities:[],commitments:[],alerts:[],networks:[],documents:[]};
async function req(path,options={}){const r=await fetch(`${API()}${path}`,options);const ct=r.headers.get('content-type')||'';const data=ct.includes('json')?await r.json():null;if(!r.ok)throw new Error(data?.error||data?.message||`Error HTTP ${r.status}`);return data;}
function message(text='',type='info'){const el=$('fcr-message');if(!el)return;el.className=`fcr-message fcr-${type}`;el.textContent=text;el.classList.toggle('hidden',!text);}
function badge(v){const s=String(v||'PENDIENTE').toUpperCase();let c='fcr-blue';if(/CRIT|ROJO|VENC|ABIERTA/.test(s))c='fcr-red';else if(/PEND|BORRADOR|MEDIO|ALTA/.test(s))c='fcr-yellow';else if(/CERR|APROB|ACTIVO|VERIFIC/.test(s))c='fcr-green';return `<span class="fcr-badge ${c}">${esc(s)}</span>`;}
async function init(){if(!state.initialized){$('fcr-activity-form')?.addEventListener('submit',createActivity);$('fcr-network-form')?.addEventListener('submit',createNetwork);$('fcr-alert-form')?.addEventListener('submit',createAlert);state.initialized=true;}$('fcr-edit-actions')?.classList.toggle('hidden',!canEdit());await load();}
async function load(){try{message('Organizando familias, actividades, compromisos y redes…');const q=new URLSearchParams({unidad:$('fcr-filter-unit')?.value||''});const [d,f,a,c,al,n,docs]=await Promise.all([req(`/dashboard?${q}`),req(`/expedientes?${q}`),req(`/actividades?${q}`),req(`/compromisos?${q}`),req(`/alertas?${q}`),req('/redes'),req('/documentos')]);state.dashboard=d;state.families=f.expedientes||[];state.activities=a.actividades||[];state.commitments=c.compromisos||[];state.alerts=al.alertas||[];state.networks=n.redes||[];state.documents=docs.documentos||[];render();message('');}catch(e){message(e.message,'error');}}
function render(){const s=state.dashboard?.resumen||{};$('fcr-stats').innerHTML=[['Familias',s.expedientes_familiares||0],['Actividades',s.actividades||0],['Compromisos abiertos',s.compromisos_abiertos||0],['Alertas abiertas',s.alertas_abiertas||0],['Redes activas',s.redes_activas||0]].map(([l,v])=>`<div class="fcr-stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('');renderFamilies();renderActivities();renderCommitments();renderAlerts();renderNetworks();renderDocuments();if(window.lucide)lucide.createIcons();}
function renderFamilies(){const box=$('fcr-families');box.innerHTML=state.families.length?state.families.slice(0,200).map(f=>`<article class="fcr-item"><div><strong>${esc(f.nombre_participante)}</strong><p>${esc(f.cuidador_principal||'Cuidador pendiente')}</p><small>${esc(f.unidad_nombre||'Sin UCA')} · ${esc(f.telefono_principal||'Sin teléfono')}</small></div>${badge(f.estado)}</article>`).join(''):'<div class="fcr-empty">Sincroniza Base Maestra para crear referencias familiares sin duplicar participantes.</div>';}
function renderActivities(){const box=$('fcr-activities');box.innerHTML=state.activities.length?state.activities.map(a=>`<article class="fcr-item"><div><strong>${esc(a.tipo).replaceAll('_',' ')} · ${esc(a.titulo)}</strong><p>${esc(a.objetivo||'Objetivo por documentar')}</p><small>${esc(a.unidad_nombre||'Sin UCA')} · ${esc(a.fecha_programada||'Sin fecha')} · ${esc(a.profesional_nombre||'Sin profesional')}</small></div><div class="fcr-actions">${badge(a.estado)}${canEdit()?`<button class="fcr-btn secondary" onclick="FamiliasRedes.prepareDocs(${a.id})">Acta y listado</button><button class="fcr-btn secondary" onclick="FamiliasRedes.addCommitment(${a.id})">Compromiso</button>`:''}</div></article>`).join(''):'<div class="fcr-empty">No hay actividades psicosociales programadas.</div>';}
function renderCommitments(){const box=$('fcr-commitments');box.innerHTML=state.commitments.length?state.commitments.map(c=>`<article class="fcr-item"><div><strong>${esc(c.titulo)}</strong><p>${esc(c.descripcion||'')}</p><small>${esc(c.unidad_nombre||'')} · responsable ${esc(c.responsable_nombre||'por asignar')} · límite ${esc(c.fecha_limite||'sin fecha')}</small></div><div class="fcr-actions">${badge(c.estado)}${canEdit()?`<button class="fcr-btn secondary" onclick="FamiliasRedes.followCommitment(${c.id})">Seguimiento</button>`:''}${canApprove()&&String(c.estado).toUpperCase()!=='CERRADO'?`<button class="fcr-btn primary" onclick="FamiliasRedes.closeCommitment(${c.id})">Cerrar</button>`:''}</div></article>`).join(''):'<div class="fcr-empty">No hay compromisos.</div>';}
function renderAlerts(){const box=$('fcr-alerts');box.innerHTML=state.alerts.length?state.alerts.map(a=>`<article class="fcr-item"><div><strong>${esc(a.tipo)}</strong><p>${esc(a.descripcion)}</p><small>${esc(a.unidad_nombre||'')} · próximo seguimiento ${esc(a.fecha_proximo_seguimiento||'sin fecha')}</small></div><div class="fcr-actions">${badge(a.nivel)}${badge(a.estado)}${canApprove()&&String(a.estado).toUpperCase()!=='CERRADA'?`<button class="fcr-btn primary" onclick="FamiliasRedes.closeAlert(${a.id})">Cerrar</button>`:''}</div></article>`).join(''):'<div class="fcr-empty">No hay alertas abiertas.</div>';}
function renderNetworks(){const box=$('fcr-networks');box.innerHTML=state.networks.length?state.networks.map(n=>`<article class="fcr-item"><div><strong>${esc(n.nombre)}</strong><p>${esc(n.tipo_actor)} · ${esc(n.territorio||n.municipio||'')}</p><small>${esc(n.contacto_nombre||'')} ${esc(n.telefono||'')}</small></div><div class="fcr-actions">${n.fecha_verificacion?badge('VERIFICADA'):badge('PENDIENTE')}${canApprove()&&!n.fecha_verificacion?`<button class="fcr-btn secondary" onclick="FamiliasRedes.verifyNetwork(${n.id})">Verificar</button>`:''}</div></article>`).join(''):'<div class="fcr-empty">No hay redes de apoyo registradas.</div>';}
function renderDocuments(){const box=$('fcr-documents');box.innerHTML=state.documents.length?state.documents.map(d=>`<article class="fcr-item"><div><strong>${esc(d.tipo_documento)}</strong><small>${esc(d.nombre_archivo)} · ${esc(d.fecha_generacion||'')}</small></div><div class="fcr-actions">${badge(d.estado)}<button class="fcr-btn secondary" onclick="FamiliasRedes.downloadDoc(${d.id},'${esc(d.nombre_archivo)}')">Descargar</button>${canApprove()&&d.estado==='BORRADOR'?`<button class="fcr-btn primary" onclick="FamiliasRedes.reviewDoc(${d.id},'revisar')">Revisar</button>`:''}</div></article>`).join(''):'<div class="fcr-empty">Los borradores de actas, listados e informes aparecerán aquí.</div>';}
async function syncFamilies(){if(!canEdit())return;const unit=$('fcr-filter-unit')?.value||prompt('Nombre exacto de la UCA (vacío para todas):')||'';try{const d=await req('/expedientes/sincronizar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unidad_nombre:unit||null})});message(`Sincronización: ${d.resultado?.creados||0} creados, ${d.resultado?.actualizados||0} actualizados.`,'success');await load();}catch(e){message(e.message,'error');}}
async function createActivity(ev){ev.preventDefault();const data={tipo:$('fcr-act-type').value,titulo:$('fcr-act-title').value,objetivo:$('fcr-act-objective').value,unidad_nombre:$('fcr-act-unit').value,fecha_programada:$('fcr-act-date').value,fecha_limite_cierre:$('fcr-act-due').value,lugar:$('fcr-act-place').value,profesional_nombre:$('fcr-act-owner').value};try{await req('/actividades',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});ev.target.reset();message('Actividad creada. La plataforma preparó borradores sin inventar resultados.','success');await load();}catch(e){message(e.message,'error');}}
async function prepareDocs(id){try{await req(`/actividades/${id}/documentos/preparar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tipos:['ACTA','LISTADO_ASISTENCIA','INFORME']})});message('Acta, listado e informe preparados como borradores.','success');await load();}catch(e){message(e.message,'error');}}
async function addCommitment(activityId){const titulo=prompt('Título del compromiso:');if(!titulo)return;const descripcion=prompt('Descripción:')||'';const due=prompt('Fecha límite (AAAA-MM-DD):')||'';try{await req('/compromisos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actividad_id:activityId,titulo,descripcion,fecha_compromiso:new Date().toISOString().slice(0,10),fecha_limite:due})});message('Compromiso registrado y enviado al Motor de Gestión.','success');await load();}catch(e){message(e.message,'error');}}
async function followCommitment(id){const resultado=prompt('Resultado del seguimiento:');if(!resultado)return;const pct=prompt('Avance reportado (0-100):','0');try{await req(`/compromisos/${id}/seguimientos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resultado,porcentaje_reportado:Number(pct||0),fecha:new Date().toISOString().slice(0,10)})});message('Seguimiento registrado.','success');await load();}catch(e){message(e.message,'error');}}
async function closeCommitment(id){const obs=prompt('Resultado de cierre validado:');if(!obs)return;try{await req(`/compromisos/${id}/cerrar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observaciones_cierre:obs})});await load();}catch(e){message(e.message,'error');}}
async function createNetwork(ev){ev.preventDefault();const data={nombre:$('fcr-net-name').value,tipo_actor:$('fcr-net-type').value,territorio:$('fcr-net-territory').value,contacto_nombre:$('fcr-net-contact').value,telefono:$('fcr-net-phone').value,correo:$('fcr-net-email').value};try{await req('/redes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});ev.target.reset();message('Red de apoyo registrada.','success');await load();}catch(e){message(e.message,'error');}}
async function verifyNetwork(id){try{await req(`/redes/${id}/verificar`,{method:'POST'});await load();}catch(e){message(e.message,'error');}}
async function createAlert(ev){ev.preventDefault();const data={tipo:$('fcr-alert-type').value,nivel:$('fcr-alert-level').value,descripcion:$('fcr-alert-description').value,unidad_nombre:$('fcr-alert-unit').value,fecha_identificacion:new Date().toISOString().slice(0,10),fecha_proximo_seguimiento:$('fcr-alert-followup').value,responsable_nombre:$('fcr-alert-owner').value};try{await req('/alertas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});ev.target.reset();message('Alerta registrada; no se cerrará automáticamente.','success');await load();}catch(e){message(e.message,'error');}}
async function closeAlert(id){const result=prompt('Resultado profesional de cierre:');if(!result)return;const evidence=prompt('Referencia de evidencia de cierre:');if(!evidence)return;try{await req(`/alertas/${id}/cerrar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resultado_cierre:result,evidencia_cierre:evidence})});await load();}catch(e){message(e.message,'error');}}
async function prepareReport(){try{const d=await req('/reportes/preparar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unidad:$('fcr-filter-unit')?.value||''})});message(`Paquete preparado: ${d.producto?.nombre_archivo||'ZIP'}`,'success');}catch(e){message(e.message,'error');}}
function downloadDoc(id,name){window.descargarArchivoAutenticado?.(`${API()}/documentos/${id}/descargar`,name).catch(e=>message(e.message,'error'));}
async function reviewDoc(id,action){try{await req(`/documentos/${id}/${action}`,{method:'POST'});await load();}catch(e){message(e.message,'error');}}
window.FamiliasRedes={init,load,syncFamilies,prepareDocs,addCommitment,followCommitment,closeCommitment,verifyNetwork,closeAlert,prepareReport,downloadDoc,reviewDoc};window.familiasRedesInit=init;
})();
