(function(){
'use strict';
const API=()=>`${window.backendUrl||window.getBackendUrl?.()||window.location.origin}/api/supervision-calidad`;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const role=()=>String(window.usuarioActual?.rol||window.authUser?.()?.rol||'').toUpperCase();
const canManage=()=>['SUPERADMIN','GERENTE','COORDINADOR','AUXILIAR_ADMINISTRATIVO'].includes(role());
const canApprove=()=>['SUPERADMIN','GERENTE','COORDINADOR'].includes(role());
const state={initialized:false,dashboard:null,visits:[],findings:[],plans:[],products:[],selectedVisit:null};
async function req(path,options={}){const r=await fetch(`${API()}${path}`,options);const ct=r.headers.get('content-type')||'';const data=ct.includes('json')?await r.json():null;if(!r.ok)throw new Error(data?.error||data?.message||`Error HTTP ${r.status}`);return data;}
function message(text='',type='info'){const el=$('sac-message');if(!el)return;const c={info:'sac-info',success:'sac-success',warning:'sac-warning',error:'sac-error'};el.className=`sac-message ${c[type]||c.info}`;el.textContent=text;el.classList.toggle('hidden',!text);}
function badge(v){const s=String(v||'PENDIENTE').toUpperCase();let c='sac-neutral';if(/CRIT|ROJO|VENC|DEVUEL|NO_CUMPLE/.test(s))c='sac-red';else if(/ALTO|ALTA|AMAR|PEND|BORRADOR|ABIERTO|PARCIAL/.test(s))c='sac-yellow';else if(/APROB|CERR|VERDE|CUMPLE|COMPLET/.test(s))c='sac-green';else c='sac-blue';return `<span class="sac-badge ${c}">${esc(s)}</span>`;}
function filters(){return {unidad:$('sac-filter-unit')?.value||'',vigencia:$('sac-filter-year')?.value||'',contrato:$('sac-filter-contract')?.value||''};}
async function init(){if(!state.initialized){$('sac-visit-form')?.addEventListener('submit',createVisit);$('sac-finding-form')?.addEventListener('submit',createFinding);state.initialized=true;}$('sac-manage-actions')?.classList.toggle('hidden',!canManage());await load();}
async function load(){try{message('Consolidando supervisiones, hallazgos y planes…');const q=new URLSearchParams(filters());const [d,v,h,p,pr]=await Promise.all([req(`/dashboard?${q}`),req(`/supervisiones?${q}`),req(`/hallazgos?${q}`),req(`/planes?${q}`),req('/productos')]);state.dashboard=d;state.visits=v.supervisiones||[];state.findings=h.hallazgos||[];state.plans=p.planes||[];state.products=pr.productos||[];render();message('');}catch(e){message(e.message,'error');}}
function render(){const s=state.dashboard?.resumen||{};$('sac-stats').innerHTML=[['Supervisiones',s.supervisiones||0],['Hallazgos abiertos',s.hallazgos_abiertos||0],['Críticos',s.hallazgos_criticos||0],['Planes abiertos',s.planes_abiertos||0],['Acciones vencidas',s.acciones_vencidas||0]].map(([l,v])=>`<div class="sac-stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('');renderVisits();renderFindings();renderPlans();renderProducts();renderUnits();if(window.lucide)lucide.createIcons();}
function unitRows(){const map=new Map();for(const v of state.visits){const k=v.unidad_nombre||'Sin UCA';const x=map.get(k)||{unidad:k,supervisiones:0,hallazgos:0,criticos:0,cumplimiento:[]};x.supervisiones++;x.cumplimiento.push(Number(v.porcentaje_cumplimiento||0));map.set(k,x);}for(const h of state.findings){const k=h.unidad_nombre||'Sin UCA';const x=map.get(k)||{unidad:k,supervisiones:0,hallazgos:0,criticos:0,cumplimiento:[]};if(!['CERRADO','DESCARTADO'].includes(String(h.estado).toUpperCase()))x.hallazgos++;if(String(h.nivel_riesgo).toUpperCase()==='CRITICO'&&!['CERRADO','DESCARTADO'].includes(String(h.estado).toUpperCase()))x.criticos++;map.set(k,x);}return [...map.values()].map(x=>({...x,cumplimiento:x.cumplimiento.length?x.cumplimiento.reduce((a,b)=>a+b,0)/x.cumplimiento.length:0,semaforo:x.criticos?'ROJO':x.hallazgos?'AMARILLO':'VERDE'}));}
function renderUnits(){const box=$('sac-units');const rows=unitRows();box.innerHTML=rows.length?rows.map(x=>`<div class="sac-unit"><div><strong>${esc(x.unidad)}</strong><small>${esc(x.supervisiones)} supervisiones · ${esc(x.hallazgos)} hallazgos abiertos</small></div>${badge(x.semaforo)}<span>${Number(x.cumplimiento||0).toFixed(1)}%</span></div>`).join(''):'<div class="sac-empty">Aún no hay datos consolidados por UCA.</div>';}
function renderVisits(){const box=$('sac-visits');if(!state.visits.length){box.innerHTML='<div class="sac-empty">No hay supervisiones programadas.</div>';return;}box.innerHTML=state.visits.map(v=>`<button class="sac-list-row" onclick="SupervisionCalidad.openVisit(${v.id})"><div><strong>${esc(v.unidad_nombre)}</strong><small>${esc(v.tipo||'SEGUIMIENTO_INTERNO')} · ${esc(v.fecha_programada||'Sin fecha')}</small></div><div>${badge(v.estado)}<small>${Number(v.porcentaje_cumplimiento||0).toFixed(1)}%</small></div></button>`).join('');}
function renderFindings(){const box=$('sac-findings');if(!state.findings.length){box.innerHTML='<div class="sac-empty">No hay hallazgos registrados.</div>';return;}box.innerHTML=state.findings.map(h=>`<article class="sac-item"><div><strong>${esc(h.codigo)} · ${esc(h.titulo)}</strong><p>${esc(h.descripcion)}</p><small>${esc(h.unidad_nombre||'Sin UCA')} · ${esc(h.componente)} · límite ${esc(h.fecha_limite||'sin fecha')}</small></div><div class="sac-actions">${badge(h.nivel_riesgo)}${badge(h.estado)}${canManage()?`<button class="sac-btn secondary" onclick="SupervisionCalidad.createPlan(${h.id})">Plan</button>`:''}${canApprove()&&String(h.estado).toUpperCase()==='RESUELTO_PENDIENTE_VALIDACION'?`<button class="sac-btn primary" onclick="SupervisionCalidad.closeFinding(${h.id})">Validar cierre</button>`:''}</div></article>`).join('');}
function renderPlans(){const box=$('sac-plans');box.innerHTML=state.plans.length?state.plans.map(p=>`<article class="sac-item"><div><strong>${esc(p.codigo)} · ${esc(p.nombre||p.objetivo)}</strong><p>${esc(p.objetivo||'Objetivo por documentar')}</p><small>${esc(p.responsable_nombre||'Sin responsable')} · límite ${esc(p.fecha_limite||'sin fecha')} · ${Number(p.progreso||0).toFixed(0)}%</small></div><div class="sac-actions">${badge(p.estado)}${canManage()?`<button class="sac-btn secondary" onclick="SupervisionCalidad.createAction(${p.id})">Acción</button><button class="sac-btn secondary" onclick="SupervisionCalidad.followPlan(${p.id})">Seguimiento</button>`:''}</div></article>`).join(''):'<div class="sac-empty">No hay planes de mejora.</div>';}
function renderProducts(){const box=$('sac-products');box.innerHTML=state.products.length?state.products.map(p=>`<article class="sac-item"><div><strong>${esc(p.tipo_producto||'Producto')}</strong><small>${esc(p.nombre_archivo)} · ${esc(p.fecha_generacion||'')}</small></div><div class="sac-actions">${badge(p.estado)}<button class="sac-btn secondary" onclick="SupervisionCalidad.downloadProduct(${p.id},'${esc(p.nombre_archivo)}')">Descargar</button></div></article>`).join(''):'<div class="sac-empty">No hay productos preparados.</div>';}
async function createVisit(ev){ev.preventDefault();if(!canManage())return message('Tu rol solo puede consultar.','warning');const data={unidad_nombre:$('sac-visit-unit').value,contrato:$('sac-visit-contract').value,vigencia:$('sac-visit-year').value,tipo:$('sac-visit-type').value,modalidad:$('sac-visit-mode').value,fecha_programada:$('sac-visit-date').value,titulo:`Supervisión ${$('sac-visit-unit').value}`,objetivo:$('sac-visit-scope').value,alcance:$('sac-visit-scope').value,supervisor_nombre:$('sac-visit-owner').value};try{const d=await req('/supervisiones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});ev.target.reset();state.selectedVisit=d.supervision;message('Supervisión creada con lista de verificación trazable.','success');await load();renderVisitDetail();}catch(e){message(e.message,'error');}}
async function openVisit(id){try{const d=await req(`/supervisiones/${id}`);state.selectedVisit=d.supervision;renderVisitDetail();}catch(e){message(e.message,'error');}}
function renderVisitDetail(){const v=state.selectedVisit;const box=$('sac-visit-detail');if(!v){box.innerHTML='<div class="sac-empty">Selecciona una supervisión.</div>';return;}box.innerHTML=`<div class="flex flex-wrap items-center justify-between gap-3"><div><h3>${esc(v.unidad_nombre)}</h3><p>${esc(v.alcance||'Sin alcance documentado')}</p></div>${badge(v.estado)}</div><div class="mt-4 space-y-2">${(v.verificaciones||[]).map(r=>`<div class="sac-check"><div><strong>${esc(r.codigo_criterio)} · ${esc(r.criterio)}</strong><small>${esc(r.componente)} · riesgo ${esc(r.nivel_riesgo)}</small></div><select class="sac-select" onchange="SupervisionCalidad.updateAnswer(${r.id},this.value)"><option ${r.resultado==='PENDIENTE'?'selected':''}>PENDIENTE</option><option ${r.resultado==='CUMPLE'?'selected':''}>CUMPLE</option><option ${r.resultado==='PARCIAL'?'selected':''}>PARCIAL</option><option ${r.resultado==='NO_CUMPLE'?'selected':''}>NO_CUMPLE</option><option ${r.resultado==='NO_APLICA'?'selected':''}>NO_APLICA</option></select></div>`).join('')}</div>${canManage()?`<button class="sac-btn primary mt-4" onclick="SupervisionCalidad.prepareProducts()">Preparar PDF · Excel · ZIP</button>`:''}`;}
async function updateAnswer(answerId,value){try{await req(`/verificaciones/${answerId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({resultado:value})});if(state.selectedVisit)await openVisit(state.selectedVisit.id);await load();}catch(e){message(e.message,'error');}}
async function createFinding(ev){ev.preventDefault();if(!canManage())return;const data={supervision_id:state.selectedVisit?.id||null,unidad_nombre:$('sac-finding-unit').value,titulo:$('sac-finding-title').value,descripcion:$('sac-finding-description').value,componente:$('sac-finding-component').value,nivel_riesgo:$('sac-finding-severity').value,fecha_limite:$('sac-finding-due').value,responsable_nombre:$('sac-finding-owner').value};try{await req('/hallazgos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});ev.target.reset();message('Hallazgo creado; permanecerá abierto hasta validación humana.','success');await load();}catch(e){message(e.message,'error');}}
async function createPlan(id){const objetivo=prompt('Objetivo del plan de mejora:');if(!objetivo)return;const nombre=prompt('Nombre del plan:','Plan de mejora')||'Plan de mejora';const due=prompt('Fecha límite (AAAA-MM-DD):')||'';try{await req('/planes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hallazgo_id:id,nombre,objetivo,fecha_limite:due})});message('Plan de mejora creado como borrador.','success');await load();}catch(e){message(e.message,'error');}}
async function createAction(id){const titulo=prompt('Acción concreta del plan:');if(!titulo)return;const due=prompt('Fecha límite (AAAA-MM-DD):')||'';const responsable=prompt('Responsable:')||'';try{await req(`/planes/${id}/acciones`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({titulo,fecha_limite:due,responsable_nombre:responsable,evidencia_requerida:true})});message('Acción creada y enviada al Motor de Gestión.','success');await load();}catch(e){message(e.message,'error');}}
async function followPlan(id){const descripcion=prompt('Descripción del seguimiento:');if(!descripcion)return;const resultado=prompt('Resultado verificado:')||'';try{await req(`/seguimientos/PLAN/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({descripcion,resultado})});message('Seguimiento registrado.','success');await load();}catch(e){message(e.message,'error');}}
async function closeFinding(id){const motivo=prompt('Motivo y evidencia de validación del cierre:');if(!motivo)return;try{await req(`/hallazgos/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({estado:'CERRADO',motivo_cierre:motivo})});message('Hallazgo cerrado con validación humana.','success');await load();}catch(e){message(e.message,'error');}}
async function prepareProducts(){const id=state.selectedVisit?.id;if(!id)return message('Selecciona primero una supervisión.','warning');try{await req(`/supervisiones/${id}/productos`,{method:'POST'});message('PDF, Excel y ZIP preparados como borradores.','success');await load();await openVisit(id);}catch(e){message(e.message,'error');}}
function downloadProduct(id,name){window.descargarArchivoAutenticado?.(`${API()}/productos/${id}/descargar`,name).catch(e=>message(e.message,'error'));}
window.SupervisionCalidad={init,load,openVisit,updateAnswer,createPlan,createAction,followPlan,closeFinding,prepareProducts,downloadProduct};window.supervisionCalidadInit=init;
})();
