"""Contenido curado: orientación operativa, nunca decisiones automáticas."""

GUIDES = {
    'dashboard': {'titulo':'Panel principal','resumen':'Resume la operación autorizada para tu rol.','necesitas':['Una sesión activa'],'pasos':['Revisa alertas y pendientes.','Abre el módulo relacionado.','Confirma cada acción dentro del módulo fuente.']},
    'base-maestra': {'titulo':'Base Maestra','resumen':'Fuente única de participantes y su vinculación a UCA.','necesitas':['Archivo autorizado o datos verificados','UCA correcta'],'pasos':['Valida el archivo antes de cargar.','Corrige inconsistencias reportadas.','Confirma la UCA y conserva la trazabilidad.']},
    'planeacion-pedagogica': {'titulo':'Planeación pedagógica','resumen':'Gestiona proyectos por UCA, planeaciones, ejecución, evidencias y borradores documentales.','necesitas':['UCA y vigencia','Docente responsable','Objetivos y evidencias esperadas'],'pasos':['Crea o abre el proyecto pedagógico de la UCA.','Registra la planeación y sus actividades.','Vincula evidencias de la ejecución.','Genera borradores y realiza la validación docente final.']},
    'gestion-pedagogica': {'titulo':'Gestión pedagógica','resumen':'Organiza entregables, calendario, documentos y seguimiento pedagógico.','necesitas':['Periodo','UCA','Responsables'],'pasos':['Consulta pendientes del periodo.','Carga el soporte en el entregable correcto.','Envía a revisión y atiende devoluciones.']},
    'talento': {'titulo':'Talento Humano','resumen':'Administra referencias del personal, perfiles y asignaciones autorizadas.','necesitas':['Datos verificados del colaborador','Rol y UCA'],'pasos':['Busca antes de crear para evitar duplicados.','Actualiza la asignación vigente.','Revisa documentos y vencimientos.']},
    'salud-nutricion': {'titulo':'Salud y Nutrición','resumen':'Registra seguimiento nutricional referencial y evidencias autorizadas.','necesitas':['Participante existente','Fecha y profesional responsable'],'pasos':['Localiza al participante en Base Maestra.','Registra la actividad o valoración.','Confirma datos y soportes antes de cerrar.']},
    'familias-redes': {'titulo':'Familias y Redes','resumen':'Gestiona acompañamientos, compromisos, redes y evidencias.','necesitas':['UCA o familia autorizada','Objetivo del acompañamiento'],'pasos':['Selecciona el registro fuente.','Documenta la acción sin emitir diagnósticos.','Define acuerdos y seguimiento verificable.']},
    'componente-psicosocial': {'titulo':'Componente Psicosocial','resumen':'Organiza caracterización, planes y seguimientos sin sustituir criterio profesional.','necesitas':['Acceso autorizado','Consentimientos y fuente verificable'],'pasos':['Consulta la caracterización vigente.','Registra el plan como borrador.','Valida profesionalmente antes de cerrar.']},
    'expediente-operativo-uca': {'titulo':'Expediente Operativo por UCA','resumen':'Consolida referencias de todos los componentes sin copiar sus datos.','necesitas':['UCA autorizada'],'pasos':['Selecciona la UCA.','Revisa semáforos y fuentes.','Corrige cada novedad en su módulo de origen.']},
    'centro-planeacion': {'titulo':'Centro de Planeación','resumen':'Consolida actividades del calendario único y sus dependencias.','necesitas':['Periodo y UCA'],'pasos':['Filtra el periodo.','Revisa responsables y dependencias.','Actualiza la actividad en su módulo fuente.']},
    'manual-operativo': {'titulo':'Manual Operativo','resumen':'Consulta documentos vigentes y su versión institucional.','necesitas':['Documento oficial vigente'],'pasos':['Comprueba código, versión y vigencia.','Consulta la sección aplicable.','No uses documentos históricos como regla vigente.']},
}

DEFAULT_GUIDE = {'titulo':'Ayuda contextual','resumen':'Te orienta en esta vista sin modificar información.','necesitas':['Identificar la tarea que deseas realizar'],'pasos':['Revisa el objetivo de la vista.','Completa únicamente datos verificables.','Confirma el resultado antes de continuar.']}
